FROM gergondet/pbuilder:@DIST@-@ARCH@

RUN echo 'deb http://packages.ros.org/ros/ubuntu @DIST@ main' > /etc/apt/sources.list.d/ros-latest.list && \
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt-get update -qq && apt-get install -qq ros-@ROS_DISTRO@-ros-base
