FROM gergondet/pbuilder:@DIST@-@ARCH@

RUN echo 'deb http://packages.ros.org/ros/ubuntu @DIST@ main' > /etc/apt/sources.list.d/ros-latest.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN apt-get update -qq
